### ISSUE TITLE
Crash when trying out bing detect api (redmine import 3268, Aleksandar Topuzović, created 02/23/2011) 

### ISSUE THREAD

**Issue by Krakonos** [Krakonos/merkaartor-oldbugs#29]
I have activated bing background, zoomed to the region, created 2 nodes selected them and then selected bing road detect
Console log

<pre>
****  "2011-02-23T15:33:47"  -- Starting  "Merkaartor/0.18 (Macintosh;0.17-dev-295-geaf99f9)" 
------- "using QT version 4.7.1 (built with 4.7.1)" 
------- "using PROJ4 version 4.7.0" 
------- "using GDAL version 1.7.2" 
------- with arguments:  ("/Users/aco/devel/merkaartor/merkaartor-sandbox/binaries/bin/merkaartor.app/Contents/MacOS/merkaartor") 
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
loadProjection  "/Users/aco/.merkaartor/Projections.xml" 
loadProjection  "/Users/aco/devel/merkaartor/merkaartor-sandbox/binaries/bin/merkaartor.app/Contents/Resources/Projections.xml" 
loadProjection  ":/Projections.xml" 
loadFilter  "/Users/aco/.merkaartor/Filters.xml" 
loadFilter  "/Users/aco/devel/merkaartor/merkaartor-sandbox/binaries/bin/merkaartor.app/Contents/Resources/Filters.xml" 
loadFilter  ":/Filters.xml" 
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
Reading symbols for shared libraries . done
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030102313.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030102313.jpeg?g=587&mkt=en-gb&n=z" 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030102311.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030102311.jpeg?g=587&mkt=en-gb&n=z" 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030103202.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030103202.jpeg?g=587&mkt=en-gb&n=z" 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030102312.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030102312.jpeg?g=587&mkt=en-gb&n=z" 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030103200.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030103200.jpeg?g=587&mkt=en-gb&n=z" 
requesting:  "ecn.t3.tiles.virtualearth.net/tiles/a12023033030102310.jpeg?g=587&mkt=en-gb&n=z" 
getting:  "http://ecn.t3.tiles.virtualearth.net/tiles/a12023033030102310.jpeg?g=587&mkt=en-gb&n=z" 
Bing Zoom:  16 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
Bing Zoom:  16 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
z:  16 ; t_x:  71335 ; t_y:  46733 
cross_x:  87.7193 ; cross_y:  91.2917 
Reading symbols for shared libraries ... done
Reading symbols for shared libraries . done
"<osmChange version="0.6" generator="magicshop"><create version="1.0.8.0" generator="magicshop"><node id="-8" lat="45.8031349" lon="15.9287539"/><node id="-9" lat="45.8040314" lon="15.9287329"/><node id="-10" lat="45.8041611" lon="15.9287167"/><node id="-11" lat="45.8041916" lon="15.9286098"/><node id="-12" lat="45.8041420" lon="15.9267054"/><way id="-2"><nd ref="-8"/><nd ref="-9"/><nd ref="-10"/><nd ref="-11"/><nd ref="-12"/></way></create></osmChange>" 

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x0000000000000000 in ?? ()
</pre>

GDB backtrace

<pre>
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000010023c9e8 in ImportExportOSC::import (this=0x7fff5fbfcb30, aLayer=0x11898de20) at ImportExport/ImportExportOSC.cpp:88
#2  0x000000010002f081 in Document::getDocumentFromXml (theXmlDoc=0x7fff5fbfcf40) at Document.cpp:963
#3  0x0000000100042a40 in bingExtract (theDocument=0x118bd1dc0, theList=0x1040b6ae0, theDock=0x104081a50, vp=@0x7fff5fbfd1e0) at Maps/FeatureManipulations.cpp:776
#4  0x00000001000781b1 in MainWindow::on_roadBingExtractAction_triggered (this=0x7fff5fbfe8f0) at MainWindow.cpp:2059
#5  0x00000001002b7d76 in MainWindow::qt_metacall (this=0x7fff5fbfe8f0, _c=QMetaObject::InvokeMetaMethod, _id=78, _a=0x7fff5fbfd3a0) at moc_MainWindow.cpp:461
#6  0x00000001039212c6 in QMetaObject::activate ()
#7  0x0000000102b53381 in QAction::triggered ()
#8  0x0000000102b54714 in QAction::activate ()
#9  0x0000000102b0a4aa in -[QCocoaMenuLoader qtDispatcherToQAction:] ()
#10 0x00007fff87c7ae9a in -[NSApplication sendAction:to:from:] ()
#11 0x00007fff87c9f41e in -[NSMenuItem _corePerformAction] ()
#12 0x00007fff87c9f188 in -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] ()
#13 0x00007fff87f23279 in -[NSMenu _internalPerformActionForItemAtIndex:] ()
#14 0x00007fff87dd4f77 in -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] ()
#15 0x00007fff87c8195c in NSSLMMenuEventHandler ()
#16 0x00007fff862a69d5 in DispatchEventToHandlers ()
#17 0x00007fff862a5f28 in SendEventToEventTargetInternal ()
#18 0x00007fff862c3beb in SendEventToEventTarget ()
#19 0x00007fff862f2d51 in SendHICommandEvent ()
#20 0x00007fff8631fb86 in SendMenuCommandWithContextAndModifiers ()
#21 0x00007fff8631fb3e in SendMenuItemSelectedEvent ()
#22 0x00007fff8631fa3e in FinishMenuSelection ()
#23 0x00007fff86300d13 in MenuSelectCore ()
#24 0x00007fff86300468 in _HandleMenuSelection2 ()
#25 0x00007fff87b527dd in _NSHandleCarbonMenuEvent ()
#26 0x00007fff87b26317 in _DPSNextEvent ()
#27 0x00007fff87b257a9 in -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ()
#28 0x00007fff87aeb48b in -[NSApplication run] ()
#29 0x0000000102b14c94 in QEventDispatcherMac::processEvents ()
#30 0x00000001039f5f14 in QEventLoop::processEvents ()
#31 0x00000001039f6234 in QEventLoop::exec ()
#32 0x00000001039f785c in QCoreApplication::exec ()
#33 0x000000010006367c in main (argc=1, argv=0x7fff5fbff3b0) at Main.cpp:262

</pre>

**Comment by Krakonos** [comment]
I always get "No valid data" when doing the same
